import PropTypes from "prop-types";
import React from "react";

const SectionTitleWithText = ({ spaceTopClass, spaceBottomClass }) => {
  return (
    <div
      className={`welcome-area ${spaceTopClass ? spaceTopClass : ""} ${
        spaceBottomClass ? spaceBottomClass : ""
      }`}
    >
      <div className="container">
        <div className="welcome-content text-center">
         

       <p>
         
         

       Waste collection is a critical step in managing waste,  Our company  is aimed at addressing this health menace, we offer a unique set of solutions. The idea is to disrupt the existing waste and recyclables space by leveraging digital technology and connect waste generators like businesses and consumers with waste aggregators and recyclers.

“Waste management in India is a $15 billion opportunity in India. Idea is to provide cloud-based full service waste and recycle enabling platform. It's focused on buying and selling recyclable, connecting recyclable generators like customers, businesses, manufacturers, and waste collectors to a network of recyclers, who are facing a shortage of reliable supply in this informal industry,”



</p>
<h1>How Black Dot will Operate </h1>
<p>
our digital technology provides many SaaS-based solutions. Our startup’s existing offerings for the waste management industry, include, a marketplace that enables transactions between waste generators, waste aggregators, recyclers with transparency and traceability. The portal makes buying, selling plastics, paper, e-waste and other recyclable wastes with digital payments, online documentation, logistics support and complete digital transaction support.
Our EPR Platform is a digital online platform that helps FMCG companies, electrical, electronics companies to manage their EPR fulfillment digitally. The platform allows brands to engage with waste generators and urban local bodies to source material digitally, thereby facilitating actionable analytics and reporting capabilities to keep things on track.

Waste picker gets a dedicated app for, enabling them access to various incentive programs to potentially alter their livelihoods.
Further, a consumer take-back and incentivization app is in process of development which will allow consumers to dispose of recyclable wastes responsibly by offering convenient pickup service and online incentives. The app will be used by corporate, schools, and colleges to run engagement programs. Consumers have an option for a doorstep pick up or drop recyclable wastes at the collection point and consumers are rewarded with points in their respective account. These points can be redeemed for gift vouchers from leading brands, incentivizing their efforts for creating a sustainable planet.

The cloud-based platform brings a host of benefits, including a hassle-free experience in facilitating recycling of large quantity of plastics, paper or e-waste generated by the industries.






</p>
        </div>
      </div>
    </div>
  );
};

SectionTitleWithText.propTypes = {
  spaceBottomClass: PropTypes.string,
  spaceTopClass: PropTypes.string
};

export default SectionTitleWithText;
